Repository pknu-wap/2022_2_WAP_APP_TEAM1, pull requests merged in 2022-10, with the labels that each got.

#18 Chore/#17/message standardization
  server/src/model/db_user.js
Labels: chore

#31 Feature/#21/social login
  README.md
  client/.idea/misc.xml
  client/app/build.gradle
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/example/witt/WittApplication.kt
  client/app/src/main/java/com/example/witt/di/AppModule.kt
  client/app/src/main/java/com/example/witt/presentation/ui/signin/SignInEvent.kt
  client/app/src/main/java/com/example/witt/presentation/ui/signin/SignInFragment.kt
  client/app/src/main/java/com/example/witt/presentation/ui/signin/SignInViewModel.kt
  client/app/src/main/res/drawable/ic_kakao_login.xml
  client/app/src/main/res/layout/fragment_sign_in.xml
  client/build.gradle
  client/gradle/wrapper/gradle-wrapper.properties
  client/settings.gradle
Labels: 최성훈, 🔥feature🔥

#38 Feature/#21/social login
  client/app/build.gradle
  client/app/src/main/java/com/example/witt/WittApplication.kt
  client/app/src/main/java/com/example/witt/presentation/ui/signin/SignInEvent.kt
  client/app/src/main/java/com/example/witt/presentation/ui/signin/SignInFragment.kt
  client/app/src/main/java/com/example/witt/presentation/ui/signin/SignInViewModel.kt
  client/app/src/main/res/drawable/ic_naver_login.xml
  client/app/src/main/res/layout/fragment_sign_in.xml
  client/app/src/main/res/values-night/themes.xml
  client/app/src/main/res/values/themes.xml
Labels: 최성훈, 🔥feature🔥

#45 Issue #44 : user 구조 변경
  .SynologyWorkingDirectory/j7g3Li
  .gitignore
  server/package.json
  server/src/app.js
  server/src/routers/index.js
  server/src/routers/user/index.js
  server/src/routers/user/user.controller.js
  server/src/routers/user/user.model.js
  server/src/routes.js
  server/src/util/file.js
  server/src/util/jwt.js
  server/src/util/multer.js
  server/src/util/rawtostr.js
Labels: data layer, domain layer, server, 이예은, 서재완, 💬review Request
